apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-deploy
  labels:
    app: form
  annotations:
spec:
  selector:
    matchLabels:
      app: form
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: form
    spec:
      containers:
        - name: form
          image: abderrahmanesellam/form:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
