apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbc-deploy
  namespace: form-builder
  labels:
    app: fb-client
spec:
  selector:
    matchLabels:
      app: fb-client
  replicas: 1
  template:
    metadata:
      labels:
        app: fb-client
    spec:
      containers:
        - name: formbuilder-client
          image: abderrahmanesellam/formbuilder-c:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "250m"
