apiVersion: v1
kind: Service
metadata:
  name: fbc-service
  namespace: form-builder
  labels:
    app: fb-client
spec:
  type: LoadBalancer
  selector:
    app: fb-client
  ports:
    - protocol: TCP
      name: http
      port: 80
