apiVersion: v1
kind: Service
metadata:
  name: form-service
  labels:
    app: form
spec:
  type: NodePort
  selector:
    app: form
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 80